Feat: 데이터 로컬스토리지에 저장
Pre-Onboarding-FE-Team07/wanted-codestates-project-7-8 pull request #14
Opened 2022-02-28 16:19 UTC by Lee-ye-ji

### PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [X] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
feature/1/localStorage -> dev

### 변경 사항
데이터들을 localStorage에 넣었습니다. 
새로고침 또는 탭을 껐다가 다시 들어가도 값이 있는 것을 확인하였습니다.

### 테스트 결과
![image](https://user-images.githubusercontent.com/59958929/156018098-77ce3527-6c87-421b-a73c-4b80e37af969.png)

### Issue
* #15

### Detail
[데이터 로컬 스토리지에 저장하기: Recoil을 이용하여](https://velog.io/@ye-ji/%EB%B0%9B%EC%95%84%EC%98%A8-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%A1%9C%EC%BB%AC-%EC%8A%A4%ED%86%A0%EB%A6%AC%EC%A7%80%EC%97%90-%EC%A0%80%EC%9E%A5%ED%95%98%EA%B8%B0-Recoil%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC)

resolved: #15

2022-03-01 00:20 UTC, jinyongp reviewed
`Good`
블로그 글까지 꼼꼼하게 작성해주셔서 이해하기 편했습니다!
`Recommend-Request`
constants 폴더엔 **상수 값**만 들어가야 하고, localStorageEffect는 함수이니 utilities 폴더 내에서 파일을 생성해 관리하는 게 더 맞는 것 같습니다.
그리고 PR 설명에서 resolved #14는 현재 PR을 참조하고 있는데 issue만 참조하도록 해야합니다. 만약 이전에 이 PR에 대한 issue를 생성해주셨다면, 이 PR은 그 issue를 resolve하는 역할을 하므로 해당 issue를 참조할 때 사용하는게 바람직해보입니다.
`Question`
이미 #6 PR에서 `atom`의 default에서 localStorage.getItem을 불러오고 있고, 데이터를 저장할 때 localStorage.setItem으로 값을 저장하고 있는데요. 해당 effect를 추가하면 값을 넣고 뺄 때 알아서 localStorage에 접근하니 더 편리하다 이렇게 이해했는데 맞을까요?

2022-03-01 01:54 UTC, dev-seomoon requested changes
**`GOOD`**
<Modal />의 saveData(), removeData() 함수에서 localstorage를 직접 업데이트하지 않고 
atom 상태만 변경해주면 돼서 좀 더 깔끔하겠네요. 
폴더 위치만 atom이나 utilities로 변경해주시면 좋을 것 같습니다.

2022-03-01 01:54 UTC, dev-seomoon commented on src/constants/localStorage.js
> +    if (savedValue != null) {
**`Recommend-Must`**
```suggestion
    if (savedValue !== null) {
```
`!=` -> `!==` 로 변경해주세요

2022-03-01 04:58 UTC, Lee-ye-ji commented
선경님과 진용님의 피드백 대로 수정을 하였습니다! 
우선 진용님 `Question`인 `해당 effect를 추가하면 값을 넣고 뺄 때 알아서 localStorage에 접근하니 더 편리하다 이렇게 이해했는데 맞을까요?`에 대한 질문은 맞다고 설명드릴 수 있습니다!!
좀 더 자세히 이야기 드리자면 `localStorage.getItem`대신에 -> `const [userList, setUserList] = useRecoilState(userStoredList);에서 userList `를 이용하여 localStorage에 있는 값을 가지고 올 수 있는 것을 확인하였습니다. 또한  
```
    onSet((newValue) => {
      localStorage.setItem(key, JSON.stringify(newValue));
    });
```  
코드를 통해 `onSet`부분은 setting의 역할과 유사해서 `setUserList(새로운 값)`을 입력하면 자동적으로 localStorage에 대한 값이 바뀌는 것 또한 확인하였습니다!

2022-03-01 05:52 UTC, jeonghun10 approved these changes

2022-03-02 00:12 UTC, exxocism approved these changes
Good: Recoil의 Effect를 사용하실 생각을 하시다니 대단하십니다.

2022-03-02 00:17 UTC, jeonghun10 approved these changes

2022-03-02 00:18 UTC, Lela12 approved these changes
OK: 확인했습니다. 문제 없습니다!

2022-03-02 00:22 UTC, ye-yo approved these changes
**Good**: 블로그 글보면서 이해에 도움이 많이 되었습니다! 고생하셨습니다!

2022-03-02 00:41 UTC, jinyongp approved these changes

2022-03-02 00:41 UTC, jinyongp commented on src/atoms/index.js
> +import { atom } from "recoil";
스타일 컨벤션에 맞게 쌍따옴표가 아닌 따옴표로 변경 부탁드립니다!

2022-03-02 00:50 UTC, merged