Feat:Axios Call
Pre-Onboarding-FE-Team07/wanted-codestates-project-7-8 pull request #16
Opened 2022-03-01 06:09 UTC by jeonghun10

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
feature/13/AxiosCall -> dev

### 변경 사항
- 공공데이터 호출과 로컬스토리지 저장
- 특이사항으로 공공데이터 호출시 localhost에서 cors에러 발생 하는부분을 프록시서버를 우회하는 부분으로 해결

### 테스트 결과
Main.jsx
JSON.parse(localStorage.getItem('dataList')) 배열로 데이터값 넘어오는 부분 확인

### Issue
resolved: #13

2022-03-01 10:05 UTC, jinyongp requested changes

2022-03-01 10:05 UTC, jinyongp commented on src/App.jsx
> +    AxiosCall()
`Recommend-Must`
함수 네이밍 컨벤션은 동사로 시작해주시고 카멜 케이스로 작성하셔야 합니다. [참고자료](https://urclass.codestates.com/8e3236dd-e909-4abe-a39e-99bc94f9d954?playlist=1013)

또한 hooks는 `use`로 시작해야 합니다. [참고자료](https://reactjs.org/docs/hooks-custom.html#using-a-custom-hook)
> **Do I have to name my custom Hooks starting with “use”?** Please do. This convention is very important. Without it, we wouldn’t be able to automatically check for violations of [rules of Hooks](https://reactjs.org/docs/hooks-rules.html) because we couldn’t tell if a certain function contains calls to Hooks inside of it.

2022-03-01 10:05 UTC, jinyongp commented on src/hooks/AxiosCall.jsx
> +};
`Recommend-Must`
파일의 맨 마지막은 개행으로 끝나야 합니다. 개행이 없다면 빨간 색 원으로 경고를 나타냅니다.

2022-03-01 10:05 UTC, jinyongp commented on src/pages/Main.jsx
> +
`Recommend-Request`
의미 없는 파일의 수정은 커밋하지 말아주세요. 병합 과정에서 충돌을 발생할 수 있습니다. 이번 PR에서는 굳이 수정하지 않으셔도 될 것 같습니다.

2022-03-01 10:05 UTC, jinyongp commented on src/hooks/AxiosCall.jsx
> +      url:`https://cors-anywhere.herokuapp.com/https://www.chungbuk.go.kr/openapi-json/pubdata/pubMapForest.do`,
`Recommend-Request`
url 부분은 상수로 분리하는게 더 좋을 것 같습니다. constants/api.js 파일에 넣으면 어떨까 싶네요! 상수의 네이밍 컨벤션은 모든 문자를 대문자로 하고 띄어쓰기는 _로 구분합니다.

2022-03-01 10:05 UTC, jinyongp commented on src/hooks/AxiosCall.jsx
> +      localStorage.removeItem("dataList");
`Question`
localStorage는 예지님이 작업하셨는데 왜 추가하셨는지 궁금하네요!

2022-03-01 10:11 UTC, dev-seomoon approved these changes

2022-03-01 10:11 UTC, dev-seomoon commented on src/App.jsx
> +  },[])
**`Recommend-Request`**
세미콜론을 넣어주세요

2022-03-01 10:11 UTC, dev-seomoon commented on src/hooks/AxiosCall.jsx
> +  })
**`Recommend-Request`**
세미콜론을 넣어주세요

2022-03-02 00:21 UTC, Lee-ye-ji approved these changes
OK: 확인했습니다. Recoil 이용해서 같이 코드 다시 작성하였습니다. 
테스트한 결과와 팀원들이 보고 사용할 수 있게 테스트를 어떻게 했는지에 대해 자세한 설명 적어주시면 감사하겠습니다!

2022-03-02 01:56 UTC, merged